#!/usr/bin/env python                    
# -*- coding: iso-8859-15 -*-

import os, sys, re


def newname(n):
    n = re.sub('\s+', '_', n)
    n = re.sub('[^\w\.]+', '_', n)
    n = re.sub('_+', '_', n)
    n = re.sub('\.+', '.', n)
    n = re.sub('^[^A-Za-z0-9]+', '', n)
    n = re.sub('[^A-Za-z0-9]+$', '', n)
    n = re.sub('[^A-Za-z0-9]+\.', '.', n)

    return n


for root, dirs, files in os.walk(sys.argv[1], topdown=False):
    for f1 in files + dirs:
        f2 = newname(f1)
        if f1 == f2:
            continue

        n1 = os.path.join(root, f1)
        n2 = os.path.join(root, f2)

        print "old: %s\nnew: %s\n" % (n1, n2)
        os.rename(n1, n2)

sys.exit(0)
# EOF
